title: 'todoフルスタックエンジニアになるためのモダンな8つのプロジェクトに挑戦してみた'
summary: 'https://qiita.com/kanye__east/items/77a9746e9b98abbb97e6'
topics: []
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2
